### ISSUE TITLE
Simulation problem

### ISSUE THREAD

**Issue by yumengna** [gregorkastner/threshtvp#1]
Dear Prof.Gregor Kastner：
         I have been doing a simple simulation, but the results seem to have some problems. My simulation is a two-dimensional var (1) model and just simply generate data and then use the function estimate_tvp() to estimate, but the estimated parameters basically do not change or fail to capture the jump of parameters. I see the TVP function seems to be updated. Can you share the modified function? Thanks so much.

**Comment by gregorkastner** [comment]
Hi there,

sorry, the package and the code have been a bit abandoned lately. But in any case, the newest code (if any) should be available here.
